### ISSUE TITLE
V11 - Error on opening report-wizard

### ISSUE THREAD

**Issue by mncoon** [fmdl/odoo_apps_public#12]
Hello,
If I click on the menu item to open the standard report, I receive this error message:

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo/odoo/models.py", line 1079, in default_get
    defaults[name] = field.default(self)
  File "/home/odoo/addons-extra/odoo_apps_public/account_standard_report/wizard/account_standard_report.py", line 146, in _get_periode_date
    today_year = fields.Date.today().year
AttributeError: 'str' object has no attribute 'year'`

The installed version is V11 enterprise.

**Comment by fmdl** [comment]
Dear you use the V12 branch, please use the V11.
